const USE_MOCK_BACKEND = process.env.USE_MOCK_BACKEND === 'true';

export const ENV_VARS = {
  GITHUB_CLIENT_ID: USE_MOCK_BACKEND ? undefined : process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: USE_MOCK_BACKEND ? undefined : process.env.GITHUB_CLIENT_SECRET,
  GITHUB_REDIRECT_URI: USE_MOCK_BACKEND ? undefined : process.env.GITHUB_REDIRECT_URI,
  GOOGLE_CLIENT_ID: USE_MOCK_BACKEND ? undefined : process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: USE_MOCK_BACKEND ? undefined : process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: USE_MOCK_BACKEND ? undefined : process.env.GOOGLE_REDIRECT_URI,
  USE_MOCK_BACKEND,
} as const;
